services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8088:80"
    env_file:
      - .env
    volumes:
      - ./cache:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_logs:/var/log/nginx
      - ./static:/usr/share/nginx/static
    depends_on:
      - tiles

  tiles:
    image: maplibre/martin:v0.8.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./martin-config.yaml:/martin-config.yaml:ro
    env_file:
      - .env
    command: --config /martin-config.yaml

  postgres:
    image: isinus/postgis-h3:$POSTGIS_H3_VERSION
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    shm_size: 1gb
