FROM postgis/postgis:16-3.4

RUN apt update
RUN apt install -y pip libpq-dev postgresql-server-dev-16
RUN pip install pgxnclient cmake
RUN pgxn install h3
RUN pip uninstall -y pgxnclient cmake
RUN apt purge -y libpq-dev postgresql-server-dev-16 pip
